program: main.c interface.c loadDatabase.c fileOperation.c menu.c databaseFunctions.c customFunctions.c app.c
	gcc -o program main.c interface.c loadDatabase.c fileOperation.c menu.c databaseFunctions.c customFunctions.c app.c
	